services:
  mongo:
    build:
      context: ./docker/mongodb_replica
      args:
        MONGO_VERSION: 8
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27019
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: mongosh
    ports:
      - '27019:27019'
    restart: unless-stopped
    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test: [CMD, mongosh, admin, --port, '27019', --eval, "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
